post:
  summary: City Created Event
  description: An event that is posted when a new city is created
  tags:
    - City
  x-internal: true
  security: []
  operationId: cityCreatedEvent
  requestBody:
    description: City
    content:
      application/json:
        schema:
          $ref: ../schemas/City.yml
  responses:
    200:
      $ref: ../responses/Webhook.yml
