description: An error returned when the request is invalid
content:
  application/json:
    schema:
      title: Bad Request Error
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          enum:
            - 400
        message:
          type: string
    examples:
      BadRequest:
        summary: Bad Request Error
        value:
          status: 400
          message: Bad Request
