description: Returns city result
content:
  application/json:
    schema:
      type: object
      required:
        - data
      properties:
        data:
          $ref: ../schemas/City.yml
    examples:
      Thurles:
        $ref: ../examples/ResponseCityThurles.yml
