description: An error returned when the requested resource cannot be found
content:
  application/json:
    schema:
      title: Not Found Error
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          enum:
            - 404
        message:
          type: string
    examples:
      NotFound:
        summary: Not Found Error
        value:
          status: 404
          message: City Not Found
