description: Returns health check result
content:
  application/json:
    schema:
      type: object
      required:
        - data
      properties:
        data:
          $ref: ../schemas/HealthCheck.yml
