description: An error returned when the requested resource cannot be found
content:
  application/json:
    schema:
      type: object
      required:
        - data
      properties:
        data:
          title: Not Found Error
          type: object
          required:
            - status
            - message
          properties:
            status:
              type: integer
              enum:
                - 404
            message:
              type: string
              enum:
                - Not Found
