description: Returns route result
headers:
  Location:
    $ref: ../headers/Location.yml
content:
  application/json:
    schema:
      type: object
      required:
        - data
      properties:
        data:
          $ref: ../schemas/Route.yml
    examples:
      ParisMilan:
        $ref: ../examples/ResponseRouteParisMilan.yml
