description: Returns route result
headers:
  Location:
    $ref: ../headers/Location.yml
content:
  application/json:
    schema:
      $ref: ../schemas/Route.yml
    example:
      $ref: ../examples/ResponseRouteParisLondon.yml
