description: An error returned when the requestor does not have access to the resource
content:
  application/json:
    schema:
      title: Unauthorized Error
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          enum:
            - 401
        message:
          type: string
    examples:
      NotFound:
        summary: Unauthorized Error
        value:
          status: 401
          message: Unauthorized
