name: Run unit tests
on:
  push:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup npmrc
        run: echo "enable-pre-post-scripts=true" >> .npmrc
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: pnpm
      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile
      - name: Bundle OpenAPI, build and validation
        run: pnpm verify
      - name: Run unit tests
        run: pnpm test
